# Version format
version: "{build}"

# Operating system (build VM template)
os: Windows Server 2016

# If the build configuration does not specify build worker image
# then Visual Studio 2015 image is used.
image: Visual Studio 2017

# Restrict to Git branches below
branches:
  only:
    - 5.x

# Scripts that run after cloning repository
install:
  - if not exist gtk-sharp-2.12.45.msi appveyor DownloadFile https://xamarin.azureedge.net/GTKforWindows/Windows/gtk-sharp-2.12.45.msi
  - msiexec /i gtk-sharp-2.12.45.msi /qn /norestart
  - if not exist XamarinStudio-5.10.3.51-0.msi appveyor DownloadFile https://xamarin.azureedge.net/studio/Windows/XamarinStudio-5.10.3.51-0.msi
  - msiexec /i XamarinStudio-5.10.3.51-0.msi /qn /norestart
  - set MDTOOL="%ProgramFiles(x86)%\Xamarin Studio\bin"
  - set PATH=%MDTOOL%;%PATH%

# Cache files until appveyor.yml is modified.
cache:
  - gtk-sharp-2.12.45.msi
  - XamarinStudio-5.10.3.51-0.msi
  - src\packages

# Run scripts below before 
before_build:
  - where msbuild
  - nuget restore src

# To run your custom scripts instead of automatic MSBuild
build_script:
  - cmd: mdtool --help # must be run at least once before doing `mdtool setup ...` (seemingly an mdtool bug)
  - cmd: msbuild /p:Configuration=DebugWin32 /t:Build src/MonoDevelop.WakaTime.sln

# Addin files qualified as artifacts
artifacts:
  - path: '**\*_Windows.mpack' # find the addin
    name: MonoDevelop_WakaTime

# Deploy to GitHub releases
deploy:
  provider: GitHub
  release: "WakaTime Addin v$(appveyor_build_version) for v5.x"
  description: "Supports\n* MonoDevelop for &#128039; Linux / ❖ Windows (*Unity3D editor*)\n* XamarinStudio for ⌘ Mac / ❖ Windows\n\nFor Windows use **_Windows.mpack** files"
  force_update: true
  auth_token:
    secure: 2+d0KgCbWQpUR8TZfzvUEzbi4NQP6F/Tt0PUwLn6jXZCyO8FnrFVFJPsFa0QBQFl
  artifact: MonoDevelop_WakaTime
  draft: false
  prerelease: false
  on:
    branch: 5.x
    appveyor_repo_tag: true

# Turn off tests
test: off
