# Version format
version: "{build}"

# Operating system (build VM template)
os: Windows Server 2016

# If the build configuration does not specify build worker image
# then Visual Studio 2015 image is used.
image: Visual Studio 2017

# Restrict to Git branches below
branches:
  only:
    - 6.x

# Scripts that run after cloning repository
install:
  - if not exist gtk-sharp-2.12.45.msi appveyor DownloadFile https://xamarin.azureedge.net/GTKforWindows/Windows/gtk-sharp-2.12.45.msi
  - msiexec /i gtk-sharp-2.12.45.msi /qn /norestart
  - if not exist XamarinStudio-6.3.0.863.msi appveyor DownloadFile https://dl.xamarin.com/MonoDevelop/Windows/XamarinStudio-6.3.0.863.msi
  - msiexec /i XamarinStudio-6.3.0.863.msi /qn /norestart
  - set MDTOOL="%ProgramFiles(x86)%\Xamarin Studio\bin"
  - set PATH=%MDTOOL%;%PATH%

# Cache files until appveyor.yml is modified.
cache:
  - gtk-sharp-2.12.45.msi
  - XamarinStudio-6.3.0.863.msi
  - src\packages

# Run scripts below before 
before_build:
  - where msbuild
  - nuget restore src

# To run your custom scripts instead of automatic MSBuild
build_script:
  - cmd: msbuild /p:Configuration=DebugWin32 /t:Build src/MonoDevelop.WakaTime.sln

# Addin files qualified as artifacts
artifacts:
  - path: ./bin/DebugWin32/*.mpack
    name: MonoDevelop.WakaTime

# Turn off tests
test: off

# Disable deployment for now
deploy: off