
// This file has been generated by the GUI designer. Do not modify.

public partial class ApiKeyForm
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Label labWakaTime;
	
	private global::Gtk.Button btnWamaTime;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Label labApi;
	
	private global::Gtk.Entry txtAPIKey;
	
	private global::Gtk.HButtonBox hbuttonbox2;
	
	private global::Gtk.Button btnOK;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget ApiKeyForm
		this.Name = "ApiKeyForm";
		this.Title = global::Mono.Unix.Catalog.GetString ("API key");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Modal = true;
		this.BorderWidth = ((uint)(10));
		this.DefaultWidth = 480;
		// Container child ApiKeyForm.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.labWakaTime = new global::Gtk.Label ();
		this.labWakaTime.Name = "labWakaTime";
		this.labWakaTime.LabelProp = global::Mono.Unix.Catalog.GetString ("Need a WakaTime account:");
		this.hbox2.Add (this.labWakaTime);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.labWakaTime]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		w1.Padding = ((uint)(6));
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnWamaTime = new global::Gtk.Button ();
		this.btnWamaTime.CanFocus = true;
		this.btnWamaTime.Name = "btnWamaTime";
		this.btnWamaTime.UseUnderline = true;
		this.btnWamaTime.Label = global::Mono.Unix.Catalog.GetString ("visit http://wakatime.com");
		this.hbox2.Add (this.btnWamaTime);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnWamaTime]));
		w2.Position = 1;
		w2.Padding = ((uint)(5));
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.labApi = new global::Gtk.Label ();
		this.labApi.Name = "labApi";
		this.labApi.LabelProp = global::Mono.Unix.Catalog.GetString ("API key");
		this.hbox1.Add (this.labApi);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.labApi]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		w4.Padding = ((uint)(6));
		// Container child hbox1.Gtk.Box+BoxChild
		this.txtAPIKey = new global::Gtk.Entry ();
		this.txtAPIKey.CanFocus = true;
		this.txtAPIKey.Name = "txtAPIKey";
		this.txtAPIKey.IsEditable = true;
		this.hbox1.Add (this.txtAPIKey);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.txtAPIKey]));
		w5.Position = 1;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbuttonbox2 = new global::Gtk.HButtonBox ();
		this.hbuttonbox2.Name = "hbuttonbox2";
		this.hbuttonbox2.Spacing = 20;
		this.hbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
		// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
		this.btnOK = new global::Gtk.Button ();
		this.btnOK.CanFocus = true;
		this.btnOK.Name = "btnOK";
		this.btnOK.UseUnderline = true;
		this.btnOK.Label = global::Mono.Unix.Catalog.GetString ("OK");
		this.hbuttonbox2.Add (this.btnOK);
		global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.btnOK]));
		w7.Expand = false;
		w7.Fill = false;
		this.vbox1.Add (this.hbuttonbox2);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbuttonbox2]));
		w8.PackType = ((global::Gtk.PackType)(1));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		w8.Padding = ((uint)(2));
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultHeight = 113;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnWamaTime.Clicked += new global::System.EventHandler (this.btnWamaTime_Clicked);
	}
}
