
// This file has been generated by the GUI designer. Do not modify.

public partial class DownloadProgressForm
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.ProgressBar progressbar1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget DownloadProgressForm
		this.Name = "DownloadProgressForm";
		this.Title = "WakaTime | Downloading..";
		this.TypeHint = ((global::Gdk.WindowTypeHint)(4));
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.BorderWidth = ((uint)(4));
		this.DefaultWidth = 480;
		this.Gravity = ((global::Gdk.Gravity)(5));
		// Container child DownloadProgressForm.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.progressbar1 = new global::Gtk.ProgressBar ();
		this.progressbar1.Name = "progressbar1";
		this.progressbar1.PulseStep = 1D;
		this.vbox1.Add (this.progressbar1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.progressbar1]));
		w1.PackType = ((global::Gtk.PackType)(1));
		w1.Position = 0;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultHeight = 98;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
