
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.WakaTime
{
	public partial class ApiKeyWindow
	{
		private global::Gtk.VBox panelMain;
		
		private global::Gtk.Table panelBody;
		
		private global::Gtk.Label labAPIKey;
		
		private global::Gtk.Entry txtAPIKey;
		
		private global::Gtk.HBox panelBottom;
		
		private global::Gtk.Fixed panelFixed;
		
		private global::Gtk.Button btnOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.WakaTime.ApiKeyWindow
			this.Name = "MonoDevelop.WakaTime.ApiKeyWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("WakaTime Settings");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.BorderWidth = ((uint)(1));
			this.DefaultWidth = 400;
			this.DefaultHeight = 60;
			// Container child MonoDevelop.WakaTime.ApiKeyWindow.Gtk.Container+ContainerChild
			this.panelMain = new global::Gtk.VBox ();
			this.panelMain.Name = "panelMain";
			this.panelMain.Spacing = 5;
			this.panelMain.BorderWidth = ((uint)(2));
			// Container child panelMain.Gtk.Box+BoxChild
			this.panelBody = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
			this.panelBody.Name = "panelBody";
			this.panelBody.RowSpacing = ((uint)(6));
			this.panelBody.ColumnSpacing = ((uint)(1));
			// Container child panelBody.Gtk.Table+TableChild
			this.labAPIKey = new global::Gtk.Label ();
			this.labAPIKey.Name = "labAPIKey";
			this.labAPIKey.LabelProp = global::Mono.Unix.Catalog.GetString ("API key");
			this.panelBody.Add (this.labAPIKey);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.panelBody [this.labAPIKey]));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child panelBody.Gtk.Table+TableChild
			this.txtAPIKey = new global::Gtk.Entry ();
			this.txtAPIKey.CanFocus = true;
			this.txtAPIKey.Name = "txtAPIKey";
			this.txtAPIKey.IsEditable = true;
			this.txtAPIKey.InvisibleChar = '●';
			this.panelBody.Add (this.txtAPIKey);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.panelBody [this.txtAPIKey]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			this.panelMain.Add (this.panelBody);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.panelMain [this.panelBody]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child panelMain.Gtk.Box+BoxChild
			this.panelBottom = new global::Gtk.HBox ();
			this.panelBottom.Name = "panelBottom";
			this.panelBottom.Spacing = 6;
			// Container child panelBottom.Gtk.Box+BoxChild
			this.panelFixed = new global::Gtk.Fixed ();
			this.panelFixed.Name = "panelFixed";
			this.panelFixed.HasWindow = false;
			this.panelBottom.Add (this.panelFixed);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.panelBottom [this.panelFixed]));
			w4.Position = 0;
			// Container child panelBottom.Gtk.Box+BoxChild
			this.btnOk = new global::Gtk.Button ();
			this.btnOk.WidthRequest = 52;
			this.btnOk.CanFocus = true;
			this.btnOk.Name = "btnOk";
			this.btnOk.UseUnderline = true;
			this.btnOk.Label = global::Mono.Unix.Catalog.GetString ("Apply");
			this.panelBottom.Add (this.btnOk);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.panelBottom [this.btnOk]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.panelMain.Add (this.panelBottom);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.panelMain [this.panelBottom]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.Add (this.panelMain);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.btnOk.Clicked += new global::System.EventHandler (this.OnBtnOkClicked);
		}
	}
}
