
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.WakaTime
{
	public partial class SettingsWindow
	{
		private global::Gtk.VBox panelMain;
		
		private global::Gtk.Table panelBody;
		
		private global::Gtk.Label labApiKey;
		
		private global::Gtk.Label labProxyAddress;
		
		private global::Gtk.Entry txtApiKey;
		
		private global::Gtk.Entry txtProxyAddress;
		
		private global::Gtk.HBox panelBottom;
		
		private global::Gtk.Fixed fixed2;
		
		private global::Gtk.Button btnOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.WakaTime.SettingsWindow
			this.Name = "MonoDevelop.WakaTime.SettingsWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("WakaTime Settings");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Modal = true;
			this.DefaultWidth = 400;
			this.DefaultHeight = 60;
			// Container child MonoDevelop.WakaTime.SettingsWindow.Gtk.Container+ContainerChild
			this.panelMain = new global::Gtk.VBox ();
			this.panelMain.Name = "panelMain";
			this.panelMain.Spacing = 6;
			this.panelMain.BorderWidth = ((uint)(2));
			// Container child panelMain.Gtk.Box+BoxChild
			this.panelBody = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.panelBody.Name = "panelBody";
			this.panelBody.RowSpacing = ((uint)(6));
			this.panelBody.ColumnSpacing = ((uint)(1));
			// Container child panelBody.Gtk.Table+TableChild
			this.labApiKey = new global::Gtk.Label ();
			this.labApiKey.Name = "labApiKey";
			this.labApiKey.LabelProp = global::Mono.Unix.Catalog.GetString ("API key");
			this.panelBody.Add (this.labApiKey);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.panelBody [this.labApiKey]));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child panelBody.Gtk.Table+TableChild
			this.labProxyAddress = new global::Gtk.Label ();
			this.labProxyAddress.Name = "labProxyAddress";
			this.labProxyAddress.LabelProp = global::Mono.Unix.Catalog.GetString ("Proxy");
			this.panelBody.Add (this.labProxyAddress);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.panelBody [this.labProxyAddress]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child panelBody.Gtk.Table+TableChild
			this.txtApiKey = new global::Gtk.Entry ();
			this.txtApiKey.CanFocus = true;
			this.txtApiKey.Name = "txtApiKey";
			this.txtApiKey.IsEditable = true;
			this.txtApiKey.InvisibleChar = '●';
			this.panelBody.Add (this.txtApiKey);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.panelBody [this.txtApiKey]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child panelBody.Gtk.Table+TableChild
			this.txtProxyAddress = new global::Gtk.Entry ();
			this.txtProxyAddress.CanFocus = true;
			this.txtProxyAddress.Name = "txtProxyAddress";
			this.txtProxyAddress.IsEditable = true;
			this.txtProxyAddress.InvisibleChar = '●';
			this.panelBody.Add (this.txtProxyAddress);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.panelBody [this.txtProxyAddress]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			this.panelMain.Add (this.panelBody);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.panelMain [this.panelBody]));
			w5.Position = 0;
			// Container child panelMain.Gtk.Box+BoxChild
			this.panelBottom = new global::Gtk.HBox ();
			this.panelBottom.Name = "panelBottom";
			this.panelBottom.Spacing = 6;
			// Container child panelBottom.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.panelBottom.Add (this.fixed2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.panelBottom [this.fixed2]));
			w6.Position = 0;
			// Container child panelBottom.Gtk.Box+BoxChild
			this.btnOk = new global::Gtk.Button ();
			this.btnOk.WidthRequest = 48;
			this.btnOk.CanFocus = true;
			this.btnOk.Name = "btnOk";
			this.btnOk.UseUnderline = true;
			this.btnOk.Label = global::Mono.Unix.Catalog.GetString ("Apply");
			this.panelBottom.Add (this.btnOk);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.panelBottom [this.btnOk]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.panelMain.Add (this.panelBottom);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.panelMain [this.panelBottom]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.Add (this.panelMain);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.btnOk.Clicked += new global::System.EventHandler (this.OnBtnOkClicked);
		}
	}
}
